{% set name = "aggregate" %}
{% set version = "0.21.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aggregate-{{ version }}.tar.gz
  sha256: 34f780da89e466d5208e55daa831f606ed2ab52bb309ab56092f177108305943

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61
    - wheel
    - pip
  run:
    - python >=3.10
    - ipython
    - cycler
    - ipykernel
    - jinja2
    - matplotlib-base >=3.5
    - numpy
    - pandas
    - psutil
    - scipy
    - sly
    - titlecase

test:
  imports:
    - aggregate
  commands:
    - pip check
  requires:
    - pip

about:
  summary: "Tools for creating and working with aggregate probability distributions."
  home: https://github.com/mynl/aggregate
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://aggregate.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - mynl
